import ActionBar from "./ActionBar";
import Alert from "./Alert";
import Badge from "./Badge";
import Breadcrumb from "./Breadcrumb";
import BreadcrumbItem from "./BreadcrumbItem";
import Button from "./Button";
import ButtonGroup from "./ButtonGroup";
import Calendar from "./Calendar";
import Combobox from "./Combobox";
import Counter from "./Counter";
import Form from "./Form";
import Icon from "./Icon";
import Identifier from "./Identifier";
import Image from "./Image";
import InlineHelp from "./InlineHelp";
import Label from "./Label";
import Layout from "./Layout";
import Link from "./Link";
import ListGroup from "./ListGroup";
import Menu from "./Menu";
import Modal from "./Modal";
import Pagination from "./Pagination";
import Panel from "./Panel";
import Popover from "./Popover";
import Popper from "./Popper";
import SearchInput from "./SearchInput";
import SideNav from "./SideNav";
import Spinner from "./Spinner";
import Status from "./Status";
import Table from "./Table";
import Tabs from "./Tabs";
import Tile from "./Tile";
import TileGrid from "./TileGrid";
import TimePicker from "./TimePicker";
import Token from "./Token";
import $fd from "./$fd";

const plugin = {
  install(vue) {
    vue.use(ActionBar);
    vue.use(Alert);
    vue.use(Badge);
    vue.use(Breadcrumb);
    vue.use(BreadcrumbItem);
    vue.use(Button);
    vue.use(ButtonGroup);
    vue.use(Calendar);
    vue.use(Combobox);
    vue.use(Counter);
    vue.use(Form);
    vue.use(Icon);
    vue.use(Identifier);
    vue.use(Image);
    vue.use(InlineHelp);
    vue.use(Label);
    vue.use(Layout);
    vue.use(Link);
    vue.use(ListGroup);
    vue.use(Menu);
    vue.use(Modal);
    vue.use(Pagination);
    vue.use(Panel);
    vue.use(Popper);
    vue.use(Popover);
    vue.use(SearchInput);
    vue.use(SideNav);
    vue.use(Spinner);
    vue.use(Status);
    vue.use(Table);
    vue.use(Tabs);
    vue.use(Tile);
    vue.use(TileGrid);
    vue.use(TimePicker);
    vue.use(Token);
    vue.use($fd);
  }
};
export default plugin;
