#!/usr/bin/env bash
IFS=$'\n\t'

rm -rf ./dist/
env VUE_APP_API_DOCS_ENABLED=true \
npx vue-cli-service build \
  --mode production \
  --target app \
  --report \
  --name fundamentalvue \
  src/docs/main.ts
